# Generated by Django 3.1.13 on 2021-12-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postmessage', models.CharField(max_length=5000)),
                ('poststatus', models.IntegerField(choices=[(2, 'PENDING'), (1, 'DELIVERED'), (0, 'BLOCKED')], default=2)),
                ('is_allowed', models.BooleanField(default=True)),
                ('postuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
