# Generated by Django 3.1.13 on 2021-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211207_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poststatus',
            field=models.IntegerField(choices=[(1, 'DELIVERED'), (0, 'BLOCKED')], default=1),
        ),
    ]
